create Database customer_behaviour;
select * from mytable limit 10

----Q1. what is the total revenue generated by male and female customer?
select gender, sum(purchase_amount_) as revenue
from mytable
group by gender

----Q2. which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount_,gender
from mytable
where discount_applied = 'Yes' and purchase_amount_ >= (select avg(purchase_amount_) from mytable)

----Q3. which are the top 5 product with the highest average review rating?
select 
item_purchased,
round(avg(review_rating),2) as "Average Product Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

----Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount_),2)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type

----Q5. Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount_),2) as avg_spend,
ROUND(sum(purchase_amount_),2) as total_revenue
from mytable
GROUP BY subscription_status
order by total_revenue, avg_spend desc;

----Q6. which five products have the highest percentage of purchases with discounts applied?
----(Which product rely heavily on discounts to sell)----
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

----Q7. Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment?
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
    end as customer_segment
from mytable
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

----Q8. What are the top 3 most purchased products within each category?
------three window function rank, dense_rank and row_number(row_number is used for different because for many items numbers are same and the 
others put rank and dense rank same)

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS items_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT 
    items_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE items_rank <= 3;


----Q9. Customers who are repeat buyers (more than five previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

----Q10.Revenue contribution of age group?
select age_group,
sum(purchase_amount_) as total_revenue
from mytable
group by age_group
order by total_revenue desc;